version: '3'
services:
  icecast:
    image: moul/icecast
    volumes:
      - logs:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ICECAST_SOURCE_PASSWORD=M8XDAuHo8YxseyiaOx9y
      - ICECAST_ADMIN_PASSWORD=CSpT2VoVLLncmSTnCGXO
      - ICECAST_PASSWORD=CBuvIeGseW0NLXP01w7Q
      - ICECAST_RELAY_PASSWORD=B0FqN22a78vEfJ5a7a8s
      - ICECAST_HOSTNAME=fm.juniorcarrillo.com
    ports:
      - 9010:8000